server:
  forward-headers-strategy: FRAMEWORK
spring:
  application:
    name: spring-boot-redis-based-session
  redis:
    host: localhost
    port: 6379
    database: 0
  session:
    timeout: 20s
logging:
  level:
    root: info
  file:
    enabled: false
